# Generated by Django 2.0.1 on 2020-10-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('A', 'audio'), ('V', 'video'), ('A/V', 'audio/video'), ('O', 'outros')], max_length=1)),
                ('status', models.CharField(choices=[('D', 'disponivel'), ('I', 'indisponivel')], max_length=1)),
                ('status_desc', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
