# Generated by Django 2.0.1 on 2020-10-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status_desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
        migrations.AddField(
            model_name='product',
            name='Descrição',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='Especificação',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='obs_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='tipo',
            field=models.CharField(choices=[('A', 'audio'), ('V', 'video'), ('AV', 'audio/video'), ('CEL', 'celular'), ('NB', 'notebook'), ('O', 'outros')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('D', 'disponivel'), ('I', 'indisponivel')], default='', max_length=1),
        ),
    ]
