# Generated by Django 2.0.1 on 2020-10-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20201015_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tipo',
            field=models.CharField(choices=[('A', 'audio'), ('V', 'video'), ('AV', 'audio/video'), ('F', 'foto'), ('CEL', 'celular'), ('NB', 'notebook'), ('O', 'outros')], default='', max_length=3),
        ),
    ]
